name = "sylvainkadjo"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/ouput/static"


[build]
command = "bun install && bunx @cloudflare/next-on-pages@latest"
